{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pestilence.serviceAccountName" . }}
  namespace: {{ include "pestilence.namespace" . }}
  labels:
    {{- include "pestilence.labels" . | nindent 4 }}
{{- end }}
